### ISSUE TITLE
Out of bounds image write in Heading::to_image

### ISSUE THREAD

**Issue by michardy** [michardy/note-digest#1]
In the wake of a708f6884e4a1a15c53555dc0dff3b2c78d6b4e9 builds crash due to out of bounds write.  

Heading.width_pix & Heading.height_pix much smaller than indicated by iterating over Heading.blobs.  This means that the image is too small or the blobs are being stretched.  

Error in iterating (see to_image method) or error resizing (see update_size_pos method)

```
getting dimensions
513-453,1940-473
iterating y; 6
iterating x; 20
printing
false
putting pix: 60, 1467
thread 'main' panicked at 'index 4852958 out of range for slice of length 4849528', /checkout/src/libcore/slice/mod.rs:672
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::slice::slice_index_len_fail
             at /checkout/src/libcore/slice/mod.rs:672
  10: <core::ops::Range<usize> as core::slice::SliceIndex<[T]>>::index_mut
             at /checkout/src/libcore/slice/mod.rs:815
  11: core::slice::<impl core::ops::IndexMut<I> for [T]>::index_mut
             at /checkout/src/libcore/slice/mod.rs:665
  12: <image::buffer::ImageBuffer<P, Container>>::get_pixel_mut
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.13.0/./src/buffer.rs:336
  13: <image::buffer::ImageBuffer<P, Container>>::put_pixel
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.13.0/./src/buffer.rs:346
  14: notedigest::Heading::to_image
             at ./src/main.rs:353
  15: notedigest::main
             at ./src/main.rs:605
  16: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  17: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:57
  18: main
  19: __libc_start_main
  20: _start


------------------
(program exited with code: 101)
```

**Comment by michardy** [comment]
Swapped width and height on lines [287](https://github.com/michardy/note-digest/blob/master/src/main.rs#L287) and [289](https://github.com/michardy/note-digest/blob/master/src/main.rs#L289)
