### ISSUE TITLE
Definition attempting to intialize content object without content

### ISSUE THREAD

**Issue by michardy** [michardy/note-digest#13]
Some images produce the following output:
```
◑: Dividing by chapterthread 'main' panicked at 'Output Generation: Error empty content object', src/main.rs:468:3
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:207
   2: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:223
             at libstd/panicking.rs:402
   3: std::panicking::begin_panic
   4: notedigest::Content::new
   5: notedigest::main
   6: std::rt::lang_start::{{closure}}
   7: main
   8: __libc_start_main
   9: _start
zsh: abort (core dumped)  target/release/notedigest
```
The important bits are:
```
   4: notedigest::Content::new
   5: notedigest::main
```

The error is caused by this operation:
``` Rust
		idea.subject = Content::new(name, page.dimensions);
```
Which triggers a the creation of a new blob and then runs update against that blob.
`update_size_pos` triggers a simple sanity check:
``` Rust
assert!(
	&self.blobs.len() > &0,
	"Output Generation: Error empty content object"
);
```

**Comment by michardy** [comment]
Possibly due to empty reference line or bad comparison.
`line` can come out empty but fixing this still does not prevent the error
